export declare const characterOfConstructionDescriptions: {
    readonly A: {
        readonly floor: "Concrete or concrete covered steel deck, fireproofed";
        readonly framing: "Structural steel columns and beams fireproofed with masonry, concrete, plaster or other incombustible material";
        readonly roof: "Formed concrete, precast slabs, concrete or gypsum on steel deck, fireproofed";
        readonly walls: "Non-bearing cavity or curtain walls, masonry, concrete, metal panels, stone";
    };
    readonly B: {
        readonly floor: "Concrete or concrete covered steel deck, fireproofed";
        readonly framing: "Reinforced concrete columns and beams";
        readonly roof: "Formed concrete, precast slabs, concrete or gypsum on steel deck, fireproofed";
        readonly walls: "Non-bearing cavity or curtain walls, masonry, concrete, metal panels, stone";
    };
    readonly C: {
        readonly floor: "Wood or steel floor joists or slab on ground";
        readonly framing: "Masonry or concrete load-bearing walls with or without plasters or non load-bearing walls with concrete, wood or steel supporting the load";
        readonly roof: "Wood or steel joists, wood or steel deck";
        readonly walls: "Brick or concrete block masonry, tilt-up formed concrete";
    };
    readonly 'C+D': {
        readonly description: "Mixtures of characters of construction";
    };
    readonly D: {
        readonly floor: "Wood or steel floor joints or slab on ground";
        readonly framing: "Wood or steel studs in bearing wall, wood or steel skeleton frame";
        readonly roof: "Wood or steel joists, wood or steel deck";
        readonly walls: "Any material except masonry or concrete";
    };
    readonly 'D/C': {
        readonly description: "Character of construction is a Class D with an exterior cladding of a higher cost than normal character of construction D specifications";
    };
    readonly 'N/A': {
        readonly description: "Not applicable";
    };
};
export declare const yearBuiltCodeNames: {
    readonly A: "Addition";
    readonly B: "Both Estimated and Renovated";
    readonly C: "Both Estimated and Addition";
    readonly D: "Both Renovated and Addition";
    readonly E: "Estimated";
    readonly M: "Estimated, Renovated and Addition";
    readonly N: "None of the above codes are applicable";
    readonly R: "Renovated";
};
export declare const conditionCodes: {
    readonly A: {
        readonly name: "Average";
        readonly ranking: 3;
    };
    readonly E: {
        readonly name: "Excellent";
        readonly ranking: 5;
    };
    readonly F: {
        readonly name: "Fair";
        readonly ranking: 2;
    };
    readonly G: {
        readonly name: "Good";
        readonly ranking: 4;
    };
    readonly P: {
        readonly name: "Poor";
        readonly ranking: 1;
    };
};
export declare const partStoreyCodeNames: {
    readonly '1': "1/4 storey";
    readonly '2': "1/2 storey";
    readonly '3': "3/4 storey";
};
export declare const splitCodeNames: {
    readonly B: "Back or Front Split";
    readonly N: "No Split";
    readonly S: "Side Split";
    readonly Y: "Yes (unconventional split style)";
};
export declare const basementFinishCodeNames: {
    readonly '2': "Recreation";
    readonly '5': "Finished";
    readonly '8': "Apartment";
    readonly A: "Apartment";
    readonly R: "Recreation";
};
export declare const heatingTypeCodeNames: {
    readonly AS: "Airtight Stove";
    readonly EL: "Electric Heating";
    readonly FA: "Forced Air";
    readonly GR: "Gravity Hot Air";
    readonly HP: "Heat Pump";
    readonly HW: "Hot Water";
    readonly IF: "In-Floor Radiant";
    readonly NO: "No Central Heating System";
    readonly OT: "Other";
    readonly PL: "Pipeless Hot Air";
    readonly RD: "Radiant Electric";
    readonly ST: "Conventional Heating Stove";
};
export declare const garageTypeCodeNames: {
    readonly A: "Attached";
    readonly B: "Basement or Built-in";
    readonly C: "Carport";
    readonly D: "Detached";
    readonly I: "Indoor";
    readonly M: "More than one type is present";
    readonly N: "No parking or No garage";
    readonly O: "Outdoor";
    readonly P: "Parking";
};
export declare const structureCodeClasses: {
    readonly 100: "Secondary";
    readonly 200: "Farm";
    readonly 300: "Residential";
    readonly 400: "Commercial";
    readonly 500: "Industrial";
    readonly 600: "Institutional";
    readonly 700: "Special Purpose";
};
export declare const structureCodeNames: {
    readonly '101': "Detached Garage";
    readonly '102': "Shed";
    readonly '103': "Greenhouse";
    readonly '104': "Workshop";
    readonly '105': "Boathouse";
    readonly '106': "Indoor Pool";
    readonly '107': "Swimming Pool Enclosures";
    readonly '108': "Outdoor Pool";
    readonly '109': "Tennis Court";
    readonly '110': "Boathouse with Residence Above";
    readonly '115': "Summer Kitchen";
    readonly '116': "Attached Garage";
    readonly '117': "Carport";
    readonly '118': "Cabin";
    readonly '119': "Detached Garage with Residence Above";
    readonly '120': "Workshop with Residence Above";
    readonly '121': "Basement Garage";
    readonly '122': "Gazebo";
    readonly '123': "Pool House/Cabana";
    readonly '124': "Private Studio (Detached)";
    readonly '125': "Outdoor Fireplace";
    readonly '126': "Outdoor Kitchen/Bar";
    readonly '127': "Outdoor Sauna/Hot Tub";
    readonly '128': "Boat Port";
    readonly '129': "Timeshare - Bachelor Unit";
    readonly '130': "Timeshare - One or More Bedroom Units";
    readonly '150': "Site Improvements";
    readonly '151': "Solarium";
    readonly '161': "Helipad";
    readonly '162': "Equipment";
    readonly '163': "Shipping Container / Sea-can";
    readonly '199': "Other Secondary Structure";
    readonly '201': "Type I Barn";
    readonly '202': "Type II Barn";
    readonly '203': "Type III Uninsulated Barn";
    readonly '204': "Type IV Insulated Barn";
    readonly '211': "Milk House";
    readonly '212': "Milking Parlour (In Barn)";
    readonly '215': "Single Storey Caged Pullets";
    readonly '216': "Broiler Barns";
    readonly '217': "High Rise Caged Layers";
    readonly '220': "Silo / Open Top";
    readonly '224': "Concrete Oxygen Limiting Silo";
    readonly '225': "Metal Oxygen Limiting Silo";
    readonly '226': "Feedstore Silo";
    readonly '227': "Harvestore Silo";
    readonly '228': "Sealstor Silo";
    readonly '229': "Horizontal Silo";
    readonly '230': "Steel Grain Bin";
    readonly '232': "Circular Bulk Feed Tank";
    readonly '234': "Rectangular Bulk Feed Tank";
    readonly '236': "Circular Steel Corn Crib";
    readonly '237': "Wood Corn Crib";
    readonly '238': "Drive Through Corn Crib";
    readonly '240': "Pack Barn";
    readonly '242': "Interior Stripper Room";
    readonly '244': "Standard Kiln";
    readonly '245': "Bulk Kiln";
    readonly '250': "Greenhouse (Freestanding)";
    readonly '252': "Greenhouse (Ridge and Valley) 2A";
    readonly '254': "Greenhouse (Ridge and Valley) 2B";
    readonly '256': "Greenhouse (Bow or Curved)";
    readonly '258': "Greenhouse (Economy)";
    readonly '260': "Fruit and Vegetable Pallet";
    readonly '262': "Fruit and Vegetable Bulk";
    readonly '264': "Mink Shed";
    readonly '266': "Prefab. Metal (Straight)";
    readonly '268': "Prefab. Metal (Slant)";
    readonly '270': "Quonset";
    readonly '275': "Miscellaneous Shed";
    readonly '282': "Rectangular Tank (Slatted Floor)";
    readonly '284': "Freestanding Rectangular Tank";
    readonly '286': "Circular Concrete Tank";
    readonly '288': "Liquid Manure Steel Tank";
    readonly '289': "Coverall";
    readonly '299': "Unspecified Farm Building";
    readonly '301': "Single Family Detached";
    readonly '302': "Single Family Semi-Detached";
    readonly '303': "Single Family Row/Town House";
    readonly '304': "Link Home (Cost Detached)";
    readonly '305': "Link Home (Cost Semi-Detached)";
    readonly '310': "Mobile Home";
    readonly '311': "Trailer";
    readonly '312': "Park Model Trailer";
    readonly '313': "Recreational Park Model Trailer";
    readonly '322': "Duplex";
    readonly '323': "Triplex";
    readonly '324': "Fourplex";
    readonly '325': "Fiveplex";
    readonly '326': "Sixplex";
    readonly '330': "Walkup Apartment, Greater Than 6 Units, 1-4 Floors";
    readonly '331': "Medium/High Rise Appartment, Greater Than 6 Units";
    readonly '340': "Row/Town House Rental";
    readonly '341': "Stacked Row/Town House Rental";
    readonly '350': "Condo Single Family Detached";
    readonly '351': "Condo Single Family Semi-Detached";
    readonly '352': "Condo Apartment in a Walkup";
    readonly '353': "Condo Apartment in a Medium/High Rise";
    readonly '354': "Condo Row/Town House";
    readonly '355': "Condo Stacked Town House";
    readonly '356': "Condominium Parking Space";
    readonly '357': "Condominium Locker";
    readonly '358': "Combined Parking and Locker Unit";
    readonly '359': "Condo - Private Workshop";
    readonly '360': "Condo - Private Wine Cellar";
    readonly '361': "Condo - Private Studio";
    readonly '362': "Condo - Private Rooftop Terrace";
    readonly '399': "Unspecified Residential Structure";
    readonly '401': "Multi-Use Multi Storey Building";
    readonly '412': "Apartment in a Non-Residential Structure";
    readonly '422': "Service Station";
    readonly '423': "Service Garage";
    readonly '424': "Automotive Show Room";
    readonly '425': "Gas Bar Kiosk";
    readonly '426': "Car Wash (Automatic)";
    readonly '427': "Automotive Specialty Shop";
    readonly '428': "Gas Bar Canopy";
    readonly '429': "Car Wash (Coin Operated)";
    readonly '433': "Retail Store";
    readonly '434': "Shopping Centre - Neighbourhood";
    readonly '435': "Shopping Centre - Community";
    readonly '436': "Shopping Centre - Regional";
    readonly '437': "Discount Store";
    readonly '438': "Big Box Retail";
    readonly '439': "Supermarket";
    readonly '442': "Conventional Restaurant";
    readonly '443': "Fast Food Restaurant";
    readonly '452': "Bank/Trust Company";
    readonly '454': "Mini Bank/Trust Building";
    readonly '460': "Assembly/Banquet Hall/Convention Centre";
    readonly '461': "Campground Ancilliary Building";
    readonly '462': "Live Theatre";
    readonly '463': "Cinema";
    readonly '464': "Drive-In Screen";
    readonly '465': "Squash/Racquetball Court";
    readonly '466': "Recreational Swimming Pool";
    readonly '467': "Marina Ancilliary Building";
    readonly '468': "Ski-Lift";
    readonly '469': "Commercial Tennis Court";
    readonly '470': "Water and/or Dry Slide";
    readonly '472': "Office Commercial";
    readonly '473': "Office Walkup, Medical and Dental";
    readonly '474': "Office, Multi-Storey";
    readonly '482': "Hotel";
    readonly '484': "Motel";
    readonly '490': "Tower";
    readonly '491': "Retail Kiosk (Indoor)";
    readonly '492': "Billboard";
    readonly '493': "Photo Kiosk (Outdoor)";
    readonly '494': "Commercial Warehouse";
    readonly '495': "Parking Garage";
    readonly '496': "Underground Parking";
    readonly '499': "Unspecified Commercial Building";
    readonly '501': "Pipelines, Compressor Station";
    readonly '502': "Bridge";
    readonly '503': "Transformer";
    readonly '504': "Pole";
    readonly '505': "Post and Beam Frame";
    readonly '506': "Wood Frame";
    readonly '507': "Prefabricated";
    readonly '508': "Load Bearing";
    readonly '509': "Steel Frame";
    readonly '510': "Pre-Engineered";
    readonly '522': "General Purpose / Miscellaneous";
    readonly '523': "Special Purpose";
    readonly '524': "Industrial Malls";
    readonly '525': "Reinforced Concrete Frame";
    readonly '526': "Precast Concrete Frame";
    readonly '527': "Wood-Framed Industrial Structure";
    readonly '528': "Mini Storage Warehouse";
    readonly '532': "Prefabricated Structure - Clr Span";
    readonly '533': "Prefabricated Structure - Multispan";
    readonly '534': "Prefabricated Structure - Arched";
    readonly '542': "Office Industrial";
    readonly '551': "Industrial Wharves and Jetties";
    readonly '552': "Miscellaneous Industrial (Less Than 5000 SQ FT)";
    readonly '553': "Conveyor Housing";
    readonly '554': "Bin/Hopper";
    readonly '555': "Gatehouse";
    readonly '556': "Tunnel";
    readonly '557': "Industrial Silo";
    readonly '558': "Lumber Storage Shed";
    readonly '559': "Tank";
    readonly '567': "Wind Turbine";
    readonly '568': "Solar Thermal (Solar Panels)";
    readonly '569': "Anaerobic Digester";
    readonly '572': "Truck Terminals";
    readonly '582': "Communications Building";
    readonly '592': "Grain Elevator";
    readonly '593': "Feed Mill";
    readonly '594': "Industrial Miscellaneous Components";
    readonly '595': "Mine";
    readonly '596': "Heavy Industry";
    readonly '597': "Standard Industry";
    readonly '598': "Warehousing";
    readonly '599': "Unspecified Industrial Building";
    readonly '600': "University/College Spec Structure";
    readonly '608': "Daycare Purpose Built";
    readonly '610': "Nursing/Retirement Home";
    readonly '620': "Hospital";
    readonly '630': "Penal/Correctional Building";
    readonly '640': "Dormitory";
    readonly '645': "Institutional Residence";
    readonly '650': "Secondary School";
    readonly '660': "Elementary School";
    readonly '661': "Portable Classroom";
    readonly '699': "Unspecified Institutional Structure";
    readonly '705': "Funeral Home Purpose Built";
    readonly '709': "Rink";
    readonly '710': "Arena";
    readonly '711': "Bowling Alley";
    readonly '725': "Armoury";
    readonly '730': "Traditional Church";
    readonly '731': "Contemporary Church";
    readonly '732': "Library";
    readonly '740': "Airplane Hanger";
    readonly '750': "Mausoleum";
    readonly '760': "Police Station";
    readonly '770': "Firehall";
    readonly '780': "Grandstand/Stadium";
    readonly '790': "Exhibit Building/Museum/Gallery";
    readonly '799': "Unspecified Special Purpose Structure";
};
